server.port= 9194
spring.application.name=task-tracker

# DB Credentails: 
spring.datasource.url= jdbc:sqlserver://localhost:1433;databaseName=deepsea_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=Admin@2025

# Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.transaction.jta.platform= enable